[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip RP2040"
#runner = "elf2uf2-rs --deploy --serial --verbose"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]
